-- ============================================================
-- WholesaleHub: Stripe Connect scaffolding
-- ============================================================
-- Adds the database surface required to integrate Stripe Connect (Express)
-- in a follow-up PR. This migration is purely additive — no columns are
-- dropped or renamed, no nullable→required conversions. Safe to apply on
-- a populated DB without backfill.
--
-- What it adds:
--   1. StripeAccountStatus enum   (PENDING, ONBOARDING, ACTIVE, RESTRICTED, REJECTED)
--   2. PaymentIntentStatus enum   (mirrors Stripe's PaymentIntent.status values)
--   3. wholesalers.stripe_account_id      TEXT UNIQUE NULL
--      wholesalers.stripe_account_status  StripeAccountStatus NOT NULL DEFAULT 'PENDING'
--      wholesalers.stripe_onboarded_at    TIMESTAMP(3) NULL
--   4. stripe_payment_intents table       1:1 with orders, FK on order_id
--      + index (status, created_at)
--
-- The corresponding Prisma client types are regenerated by
-- `npx prisma generate`. New schema fields use camelCase in TS / snake_case
-- in SQL via Prisma's `@@map` convention already established in the project.
-- ============================================================

-- 1. StripeAccountStatus enum -------------------------------------------------
CREATE TYPE "StripeAccountStatus" AS ENUM (
  'PENDING',
  'ONBOARDING',
  'ACTIVE',
  'RESTRICTED',
  'REJECTED'
);

-- 2. PaymentIntentStatus enum -------------------------------------------------
-- Wire values mirror Stripe's `payment_intent.status` so the webhook handler
-- can map directly without translation.
CREATE TYPE "PaymentIntentStatus" AS ENUM (
  'REQUIRES_PAYMENT_METHOD',
  'REQUIRES_CONFIRMATION',
  'REQUIRES_ACTION',
  'PROCESSING',
  'SUCCEEDED',
  'REQUIRES_CAPTURE',
  'CANCELED',
  'FAILED'
);

-- 3. wholesalers — Stripe Connect account fields ------------------------------
-- All three columns are nullable / have defaults so the migration is safe to
-- apply without backfill. Existing rows get NULL / 'PENDING' by default.
ALTER TABLE "wholesalers"
  ADD COLUMN "stripeAccountId"     TEXT,
  ADD COLUMN "stripeAccountStatus" "StripeAccountStatus" NOT NULL DEFAULT 'PENDING',
  ADD COLUMN "stripeOnboardedAt"   TIMESTAMP(3);

-- Unique on stripeAccountId — prevents two wholesalers ever pointing at the
-- same Stripe Connect account due to a bug in `createConnectedAccount`.
CREATE UNIQUE INDEX "wholesalers_stripeAccountId_key"
  ON "wholesalers" ("stripeAccountId");

-- 4. stripe_payment_intents ---------------------------------------------------
CREATE TABLE "stripe_payment_intents" (
  "id"             TEXT                  NOT NULL,
  "orderId"        TEXT                  NOT NULL,
  "stripeIntentId" TEXT                  NOT NULL,
  "amount"         DECIMAL(10, 2)        NOT NULL,
  "applicationFee" DECIMAL(10, 2)        NOT NULL,
  "currency"       TEXT                  NOT NULL DEFAULT 'usd',
  "status"         "PaymentIntentStatus" NOT NULL DEFAULT 'REQUIRES_PAYMENT_METHOD',
  "clientSecret"   TEXT,
  "lastError"      TEXT,
  "capturedAt"     TIMESTAMP(3),
  "refundedAt"     TIMESTAMP(3),
  "createdAt"      TIMESTAMP(3)          NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"      TIMESTAMP(3)          NOT NULL,

  CONSTRAINT "stripe_payment_intents_pkey" PRIMARY KEY ("id")
);

-- 1:1 with orders — orderId is unique. We could lift this to N:1 later
-- (auth + recapture) but defer until we actually need it.
CREATE UNIQUE INDEX "stripe_payment_intents_orderId_key"
  ON "stripe_payment_intents" ("orderId");

-- Stripe `pi_*` ids are unique within an account; defending against duplicate
-- webhook inserts.
CREATE UNIQUE INDEX "stripe_payment_intents_stripeIntentId_key"
  ON "stripe_payment_intents" ("stripeIntentId");

-- Composite index for "show me all stuck payments older than X" queries.
CREATE INDEX "stripe_payment_intents_status_createdAt_idx"
  ON "stripe_payment_intents" ("status", "createdAt");

-- FK on orderId. ON DELETE/UPDATE behaviour matches the rest of the project
-- (Prisma default — referential action NO ACTION; explicit RESTRICT below
-- for clarity / parity with `prisma migrate dev` output).
ALTER TABLE "stripe_payment_intents"
  ADD CONSTRAINT "stripe_payment_intents_orderId_fkey"
  FOREIGN KEY ("orderId") REFERENCES "orders" ("id")
  ON DELETE RESTRICT ON UPDATE CASCADE;
